### ISSUE TITLE
Incorrect authentication success result 

### ISSUE THREAD

**Issue by jrpedrianes** [firstandthird/hapi-api-key#9]
Following the hapi server auth documentation (https://hapijs.com/api#-serverauthapi) a success authentication must be return the credentials (using h.authenticated), but the plugin only try to continue the process. This do that Hapi throw an error when try to process the auth response (https://github.com/hapijs/hapi/blob/master/lib/auth.js#L94).

I think that is only need to change this code (https://github.com/firstandthird/hapi-api-key/blob/master/index.js#L61): 
`
if (isValid && credentials !== undefined) {
  return h.continue;
}
`
For this:
`
if (isValid && credentials !== undefined) {
  return h.authenticated({
    credentials: credentials
  });
}
`

**Comment by jgallen23** [comment]
thanks @jrpedrianes!

@orthagonal can you take a look?

**Comment by jrpedrianes** [comment]
Some news on this?

**Comment by orthagonal** [comment]
Added a test and fix for this: https://github.com/firstandthird/hapi-api-key/pull/10

**Comment by jrpedrianes** [comment]
do you have scheduled a new release with this fix?
